### ISSUE TITLE
[BUG] OnSurface color is used for text placed to tab with Background color

### ISSUE THREAD

**Issue by slavap** [zeshuaro/appainter#1010]
### Platform

Web

### Steps to Reproduce

![image](https://github.com/zeshuaro/appainter/assets/4129763/7f63de2d-38da-4bd1-8289-650574117b5c)

### Expected behaviour

Text color has to be orange in this example case.

### Actual behaviour

OnSurface color used for text, which is wrong.

**Comment by zeshuaro** [comment]
I believe this is the expected behaviour from Flutter, see this code here: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/typography.dart#L189-L190

**Comment by slavap** [comment]
@zeshuaro Strange. But sounds like background/onBackground will be deprecated soon, because Material design 3 is now switched to different variants of surface colors:
![image](https://github.com/zeshuaro/appainter/assets/4129763/e500d265-4597-4288-be24-02c34eccfed5)
