### ISSUE TITLE
[FEATURE] Please add Filled and Tonal buttons to clearly see how theme changes affect them.

### ISSUE THREAD

**Issue by slavap** [zeshuaro/appainter#1066]
### What kind of feature are you missing?

https://m3.material.io/components/buttons/overview

![image](https://github.com/zeshuaro/appainter/assets/4129763/d3b0c2d8-09e3-4428-b0f0-59d488302faf)

**Comment by zeshuaro** [comment]
I've added a new editor for customising the filled button. However, It doesn't seem like there is a dedicated theme data object for customising the tonal button. So I'm going to leave it there until there is one.

Closed by #1270
