### ISSUE TITLE
[BUG] No named parameter with the name 'selectedRowColor' when using the exported theme 

### ISSUE THREAD

**Issue by doudar** [zeshuaro/appainter#1122]
### Platform

Web

### Steps to Reproduce

My app builds fine in the development environment, but when I build it with actions, it fails with: Error: No named parameter with the name 'selectedRowColor' 

Full app is at: [doudar/SS2kConfigApp](https://github.com/doudar/SS2kConfigApp)

### Expected behaviour

It should build the same with actions. 

### Actual behaviour

It doesn't build

### Additional Context

Thanks for any input!

```"Install Android SDK Build-Tools 30.0.3 (revision: 30.0.3)" finished.
../../../hostedtoolcache/flutter/3.19.3-stable/x64/.pub-cache/hosted/pub.dev/json_theme-4.0.3+5/lib/src/codec/theme_decoder.dart:11042:9: Error: No named parameter with the name 'selectedRowColor'.
        selectedRowColor: decodeColor(
        ^^^^^^^^^^^^^^^^
../../../hostedtoolcache/flutter/3.19.3-stable/x64/packages/flutter/lib/src/material/theme_data.dart:268:11: Context: Found this candidate, but the arguments don't match.
  factory ThemeData({
          ^
../../../hostedtoolcache/flutter/3.19.3-stable/x64/.pub-cache/hosted/pub.dev/json_theme-4.0.3+5/lib/src/codec/theme_encoder.dart:6417:47: Error: The getter 'selectedRowColor' isn't defined for the class 'ThemeData'.
 - 'ThemeData' is from 'package:flutter/src/material/theme_data.dart' ('../../../hostedtoolcache/flutter/3.19.3-stable/x64/packages/flutter/lib/src/material/theme_data.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'selectedRowColor'.
        'selectedRowColor': encodeColor(value.selectedRowColor),
                                              ^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception ```

**Comment by zeshuaro** [comment]
Hi @doudar, thanks for raising the issue. Can you try using the latest version of `json_theme` in your app which is version 6.4.1?
https://pub.dev/packages/json_theme

**Comment by doudar** [comment]
> Hi @doudar, thanks for raising the issue. Can you try using the latest version of `json_theme` in your app which is version 6.4.1?
> https://pub.dev/packages/json_theme

Thanks - yes, it seems to have been an issue with different flutter versions vs different json_theme versions. I believe I have it sorted now.

Perhaps, if you know the Appainter maintainer, you could post an issue there (or I can) to update the help information (usage) on their site/app to add ^6.0.0 instead of the current ^4.0.0 .

Thanks for the response! I love what you're doing here!

You can close this issue at your leisure.
