### ISSUE TITLE
[BUG] Build release fail

### ISSUE THREAD

**Issue by dbof10** [zeshuaro/appainter#1280]
### Platform

All platforms

### Steps to Reproduce

1. 
2.
3.

### Expected behaviour

Build no error

### Actual behaviour

This application cannot tree shake icons fonts. It has non-constant instances of IconData at the following locations:
  - file://.pub-cache/hosted/pub.dev/json_theme-6.5.0+1/lib/src/codec/theme_decoder.dart:5465:16
Target web_release_bundle failed: Error: Avoid non-constant invocations of IconData or try to build again with --no-tree-shake-icons.

**Comment by zeshuaro** [comment]
Can you clarify what exactly are you trying to build? Is it your application using the exported theme file from Appainter? 

The error message also suggests you can try again with `--no-tree-shake-icons`, have you tried that?
