### ISSUE TITLE
[FEATURE] Export as dart code

### ISSUE THREAD

**Issue by winterdl** [zeshuaro/appainter#224]
### What kind of feature are you missing?

Have option to exporting as dart code or json, thanks you!

**Comment by zeshuaro** [comment]
Hi @winterdl, thanks for raising this issue. A similar issue has actually been raised before, see #70. The decision to output the theme in a json format is as follow:

1. Having the theme in json format is very easy for the app to serialize and/or deserialize it. This makes theme import and export very easy.
2. To output dart code, this would require a lot of effort to achieve it, not to mention to also support parsing the dart code back into the app for theme import support.

Unless there's a straightforward method for serializing and deserializing dart code, this feature probably won't be added.
