### ISSUE TITLE
[FEATURE] Input Border

### ISSUE THREAD

**Issue by hosttcp** [zeshuaro/appainter#236]
### What kind of feature are you missing?

Hi. Thank you for your work! Pls add support for **outline input border** to **input decoration**

### Additional context

![image](https://user-images.githubusercontent.com/22972392/149314739-a6165688-4c85-403a-954e-ecf3d698a71d.png)

**Comment by zeshuaro** [comment]
Hey @hosttcp, thanks for raising this feature request. I've just added a dropdown within "Input Decoration" to allow you to select between underline or outline input border. This feature is now available on the web app, and will be available on the desktop apps in the next release.

PS I'm aware there are a few different options that you can customise with the input border. But that requires more changes. I'll be looking into it next when I have time 🙂
