### ISSUE TITLE
[FEATURE] Add an option to set a global font

### ISSUE THREAD

**Issue by CaptainDario** [zeshuaro/appainter#247]
### What kind of feature are you missing?

Thank you for this nice package.

To my mind, it would be very nice if one can set a global font.
Right now one has to change all entries from "Segoe UI" which is kind of annoying. It also seems like it has no effect to remove all `FontFamily`-entries.

**Comment by CaptainDario** [comment]
Thank you alot!
I am developing a Japanese app and there it is crucial that the font actually shows Japanese characters and not Chinese ones.

**Comment by zeshuaro** [comment]
Hmmm unfortunately the scrolling performance doesn't seem to be too great with that long list of fonts. I'll need to fix it up to make it more usable.

**Comment by zeshuaro** [comment]
Hello again @CaptainDario, I've just merged in an update to address the scrolling issue. Hopefully it's more usable now 🙂 

More details in #273
