### ISSUE TITLE
Package your app with flutter_distributor.

### ISSUE THREAD

**Issue by lijy91** [zeshuaro/appainter#286]
### What kind of feature are you missing?

[flutter_distributor](https://github.com/leanflutter/flutter_distributor) It is a packaging and publishing tool specially developed for flutter. Can it be used for packaging in this project?

**Comment by zeshuaro** [comment]
Hey @lijy91, thanks for the suggestion. Would you be able to share some of the advantages using `flutter_distributor` over to simply running the `flutter build` command?

**Comment by lijy91** [comment]
It can package apps as installation packages for desktop systems such as dmg, exe, deb, and can be easily released to github release

**Comment by zeshuaro** [comment]
I see thanks for sharing the info. At the moment I don't see any problems with packaging and releasing the app as a standalone/portable app. And I think most people are using the webapp anyway. So will leave it as is and will look into this if it becomes more favourable.
