### ISSUE TITLE
[BUG] Advanced theme export does not output correct ColorScheme

### ISSUE THREAD

**Issue by kirinnee** [zeshuaro/appainter#335]
### Platform

Web

### Steps to Reproduce

1. Go to appainter.dev
2. Go to advance and edit
3. Press export

### Expected behaviour

Export advanced configured theme as appainter_theme.json

### Actual behaviour

export basic theme

### Additional Context

No context

**Comment by zeshuaro** [comment]
Hey @kirinnee, thanks for raising this issue.

Would you be able share more information on this? I tested this just then and didn't see any issues. So I'm curious on how did you determine that the advanced configuration was not exported?

**Comment by zeshuaro** [comment]
> The colorScheme field will still use ff2196f3 as primary and secondary color.

Thanks for point that out, I can see the same behaviour. I'll look into this.

> Also, not sure if it is intended, but additional configurations, such as AppBar configurtaion/Button configuration are only added if I manually change them.

Yes this is the intended behaviour. Take the `backgroundColor` property in `AppBar` for example, if you look at their [docs](https://api.flutter.dev/flutter/material/AppBar/backgroundColor.html), this is how it resolves what color to use:

> If null, then the [AppBarTheme.backgroundColor](https://api.flutter.dev/flutter/material/AppBarTheme/backgroundColor.html) is used. If that value is also null, then [AppBar](https://api.flutter.dev/flutter/material/AppBar-class.html) uses the overall theme's [ColorScheme.primary](https://api.flutter.dev/flutter/material/ColorScheme/primary.html) if the overall theme's brightness is [Brightness.light](https://api.flutter.dev/flutter/dart-ui/Brightness.html), and [ColorScheme.surface](https://api.flutter.dev/flutter/material/ColorScheme/surface.html) if the overall theme's [brightness](https://api.flutter.dev/flutter/material/AppBar/brightness.html) is [Brightness.dark](https://api.flutter.dev/flutter/dart-ui/Brightness.html).

And so if you didn't make any changes to the `AppBarTheme`, then the output file will not contain any configurations for it. And will fallback to how Flutter defaults to resolve its color. Hope this makes sense 🙂
