### ISSUE TITLE
[BUG] Setting Brightness appears to reset the settings

### ISSUE THREAD

**Issue by SilkyPantsDan** [zeshuaro/appainter#342]
### Platform

Web

### Steps to Reproduce

1. Open app, notice Brightness setting
2. Set Seed colour to anything, notice state updates
3. Change Brightness setting
4. Notice settings are reset to default colours (seed color stays the same)
5. Change Brightness setting back to the original setting
6. Notice settings are reset to default colours (seed color stays the same) 

### Expected behaviour

Seed color changes should persist between brightness settings

### Actual behaviour

Seed color changes do not persist between brightness settings, and appear to reset to default colors

**Comment by zeshuaro** [comment]
Hey @SilkyPantsDan, thanks for raising this issue. It is the intended behaviour for the properties to reset when you toggle the brightness, as some of them need to be updated to fit with the brightness. And so it seems like there is a bug with the seed colour not being reset.

To improve the user experience, perhaps I can add a warning when users decide to toggle the brightness that them properties will be reset.
