### ISSUE TITLE
[BUG] Negative values cannot be entered for letter spacing.

### ISSUE THREAD

**Issue by ozozozd** [zeshuaro/appainter#398]
### Platform

MacOS

### Steps to Reproduce

1. Try typing -1.5 for Advanced > Body Text 1 > Letter Spacing
2. Observe that `-` character won't print.

### Expected behaviour

`-` character prints.

### Actual behaviour

`-` character won't print.

**Comment by zeshuaro** [comment]
Hey @ozozozd, thanks for raising this issue. I will look into this. Looks like word spacing should also be allowed to have negative values. Do you know if there's any other fields that should allow negative values?
