### ISSUE TITLE
Extended colors

### ISSUE THREAD

**Issue by benjaminschreck** [zeshuaro/appainter#411]
### What kind of feature are you missing?

Adding extended colors to the themes colorscheme. 
A feature like https://material-foundation.github.io/material-theme-builder/#/custom

**Comment by zeshuaro** [comment]
Hey @benjaminschreck, thanks for raising this issue. The basic editor mode already supports editing all the colours available for a colour scheme. Does that meet your requirements?

FYI, most of the Flutter widgets do not support the extended colours yet, and so you won't see the effects of these colours.

**Comment by benjaminschreck** [comment]
My requirement would be to add additional colors like a success color for example.

**Comment by zeshuaro** [comment]
I think I understand better now what you're after. [ColorScheme](https://api.flutter.dev/flutter/material/ColorScheme-class.html) doesn't actually contain any extended/additional colours. The "Extended Colours" on the Material Theme Builder you shared are just to display a set of complementary tones for the colours.

My follow-up question is how do you intend to use the additional colours? Are you simply after the set of complementary tones for the colours?
