### ISSUE TITLE
Question: Is there a plugin for Intellij that will show the colours in the gutter?

### ISSUE THREAD

**Issue by NZPIF** [zeshuaro/appainter#415]
Wondering if anyone using this tool can suggest an extension to make it easy to visualise the ARGB colours in intellij?

**Comment by zeshuaro** [comment]
Hey @NZPIF, thanks for raising this issue. But does your question have anything to do with Appainter?

**Comment by NZPIF** [comment]
Not directly and I appreciate this probably isn't the right place to ask but google etc weren't helping. I will be more inclined to use the export files from appainter if they are user friendly in the editors.

**Comment by zeshuaro** [comment]
I would suggest you to ask this in r/FlutterDev on Reddit 🙂
