### ISSUE TITLE
[BUG] Error: Type 'Overflow' not found

### ISSUE THREAD

**Issue by felipedrumond** [zeshuaro/appainter#426]
### Platform

All platforms

### Steps to Reproduce

1. I'm just trying Flutter out and after configuring the pubspec.yaml of an app I just created using "Flutter: New Project". Here's my yaml file:
![image](https://user-images.githubusercontent.com/17038136/176989135-77ac17ad-f60d-442b-8b83-c13e4837b617.png)

3. my main.dart
![image](https://user-images.githubusercontent.com/17038136/176989208-9384cfd9-2803-44ea-8e2c-4bbb165e6ed4.png)

4. When I try to build the app, it fails
![image](https://user-images.githubusercontent.com/17038136/176989102-5f19a36a-11c1-4d61-acc3-137a44d57c47.png)

### Expected behaviour

I'd expect it to run fine as the instructions were followed.

### Actual behaviour

Build fails.

### Additional Context

Prior to the changes described in the USAGE.md, the app builds fine and runs fine.
This is my env:
![image](https://user-images.githubusercontent.com/17038136/176989289-642640e4-0035-4d88-8e66-3186bcebc315.png)

**Comment by zeshuaro** [comment]
Hey @felipedrumond, thanks for raising the issue. Apologies that `USAGE.md` might be out-of-date. 

Would you be able to try installing the latest version of the package `json_theme`, i.e. `json_theme: ^4.0.0+4` and see if it resolves your issue?

**Comment by felipedrumond** [comment]
@zeshuaro Thank you! Updating to that version fixed the issue.
