### ISSUE TITLE
[BUG] web app attempting to load Flutter twice

### ISSUE THREAD

**Issue by ditman** [zeshuaro/appainter#673]
### Platform

Web

### Steps to Reproduce

1. Open https://appainter.dev
2. Look at the "Elements" tab of the browser devtools of your choice.

### Expected behaviour

There should only be one `flt-glass-pane` element in the page.

### Actual behaviour

There's two `flt-glass-pane` elements on the page.

### Flutter doctor output

n/a

### Additional Context

There's a problem in the `web/index.html` file. It is attempting to load Flutter twice (one via `flutter.js`, the other with the older mechanism of loading with a big inline script).

The fix for this would be to remove the following:

https://github.com/zeshuaro/appainter/blob/main/web/index.html#L77-L140

(And add a small script with the `var serviceWorkerVersion = null` line next to the one that is loading `flutter.js`.

See [this](https://docs.flutter.dev/development/platform-integration/web/initialization).

**Comment by zeshuaro** [comment]
@ditman Thanks so much for raising this issue with the relevant fix for it. I've raised a PR to address this.

**Comment by ditman** [comment]
@zeshuaro I would have sent you a PR (and with a small loading animation), but I cannot send patches to AGPL-licensed repos 😅

**Comment by zeshuaro** [comment]
No worries. May I ask why you can't contribute to AGPL licensed repos?

**Comment by ditman** [comment]
It's company policy 🤷

https://opensource.google/documentation/reference/patching#forbidden

(I haven't checked if it affects my personal time (probably *not*), but in my personal time I don't have much time left to keep coding!)
